### ISSUE TITLE
Areas of improvement.

### ISSUE THREAD

**Issue by Kingjosh007** [alexander16108/todo-List#5]
Hi @alexander16108 
 Thank you for submitting your code for review. 
Good job so far, but there are a few things suggested by [Stephanie](https://github.com/Ugboaja-Uchechi) and I  that you may want to consider:

**Note:** All the suggested changes/updates here relate to [your default branch](https://github.com/alexander16108/todo-List/tree/AddRemove) and are made in light of [the project requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md).

- We were not able to test your project fully from the live link you provided. Kindly deploy your updated code.

- In the README file, the Getting Started sections should provide the steps to get your project running on someone else's computer. Kindly update that section.

Happy coding, and happy new month!

**Comment by alexander16108** [comment]
thank you I have resolved both issues and hope you can check it out
